#!/bin/bash

IMAGE_NAME="zatitech/assuremappingtools"
TAG="0.5-5-g829bcfb"

xhost + && \
docker run -it --rm \
--env="DISPLAY=$DISPLAY" \
--volume=/tmp/.X11-unix:/tmp/.X11-unix \
--device=/dev/dri/card0:/dev/dri/card0 \
--privileged \
${IMAGE_NAME}:${TAG}
