#!/bin/bash
# exit when any command fails
set -e

if [ -z "$1" ]
  then
    echo "No specific tag provided using 'master'"
    TAG=master
else
    echo "tag specified using '$1'"
    TAG=$1
fi

xhost + && \
docker run -it --rm \
--env="DISPLAY=$DISPLAY" \
--volume=/tmp/.X11-unix:/tmp/.X11-unix \
--device=/dev/dri/card0:/dev/dri/card0 \
--privileged \
zatitech/assuremappingtools:${TAG}